#############################################################################
# Makefile for building: Calculator.app/Contents/MacOS/Calculator
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  ../Calculator/Calculator.pro
# Template: app
# Command: /Users/Darek/Qt/5.15.0/clang_64/bin/qmake -o Makefile ../Calculator/Calculator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qml_debug CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I../Calculator -I. -I../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers -I../Qt/5.15.0/clang_64/lib/QtGui.framework/Headers -I../Qt/5.15.0/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Qt/5.15.0/clang_64/mkspecs/macx-clang -F/Users/Darek/Qt/5.15.0/clang_64/lib
QMAKE         = /Users/Darek/Qt/5.15.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/Darek/Qt/5.15.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/Darek/Qt/5.15.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Calculator1.0.0
DISTDIR = /Users/Darek/build-Calculator-Desktop_Qt_5_15_0_clang_64bit-Profile/.tmp/Calculator1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/Darek/Qt/5.15.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Darek/Qt/5.15.0/clang_64/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Calculator/dialog.cpp \
		../Calculator/main.cpp \
		../Calculator/mainwindow.cpp moc_dialog.cpp \
		moc_mainwindow.cpp
OBJECTS       = dialog.o \
		main.o \
		mainwindow.o \
		moc_dialog.o \
		moc_mainwindow.o
DIST          = ../Qt/5.15.0/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.15.0/clang_64/mkspecs/qdevice.pri \
		../Qt/5.15.0/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.15.0/clang_64/mkspecs/common/unix.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/mac.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/macx.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/clang.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.15.0/clang_64/mkspecs/qconfig.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.15.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.15.0/clang_64/mkspecs/features/spec_post.prf \
		../Calculator/.qmake.stash \
		../Qt/5.15.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/toolchain.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/resolve_target.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/unix/separate_debug_info.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qtquickcompiler.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/mac.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qt.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/resources_functions.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/resources.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/moc.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/uic.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qmake_use.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/lex.prf \
		../Calculator/Calculator.pro ../Calculator/dialog.h \
		../Calculator/mainwindow.h ../Calculator/dialog.cpp \
		../Calculator/main.cpp \
		../Calculator/mainwindow.cpp
QMAKE_TARGET  = Calculator
DESTDIR       = 
TARGET        = Calculator.app/Contents/MacOS/Calculator

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/Darek/Calculator/Calculator.pro


include /Users/Darek/Qt/5.15.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Calculator.app/Contents/MacOS/Calculator: ui_dialog.h ui_mainwindow.h $(OBJECTS)  
	@test -d Calculator.app/Contents/MacOS/ || mkdir -p Calculator.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	mkdir -p /Users/Darek/build-Calculator-Desktop_Qt_5_15_0_clang_64bit-Profile/Calculator.app.dSYM/Contents/Resources/DWARF && dsymutil Calculator.app/Contents/MacOS/Calculator --flat -o Calculator.app.dSYM/Contents/Resources/DWARF/Calculator && strip -S Calculator.app/Contents/MacOS/Calculator

Makefile: ../Calculator/Calculator.pro ../Qt/5.15.0/clang_64/mkspecs/macx-clang/qmake.conf ../Qt/5.15.0/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.15.0/clang_64/mkspecs/qdevice.pri \
		../Qt/5.15.0/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.15.0/clang_64/mkspecs/common/unix.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/mac.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/macx.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/clang.conf \
		../Qt/5.15.0/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.15.0/clang_64/mkspecs/qconfig.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.15.0/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.15.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.15.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.15.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/toolchain.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/resolve_target.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/unix/separate_debug_info.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qtquickcompiler.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/mac.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qt.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/resources_functions.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/resources.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/moc.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/uic.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/qmake_use.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.15.0/clang_64/mkspecs/features/lex.prf \
		../Calculator/Calculator.pro \
		../Qt/5.15.0/clang_64/mkspecs/macx-clang/Info.plist.dSYM.in \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../Qt/5.15.0/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../Qt/5.15.0/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../Calculator/Calculator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qml_debug CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info
../Qt/5.15.0/clang_64/mkspecs/features/spec_pre.prf:
../Qt/5.15.0/clang_64/mkspecs/qdevice.pri:
../Qt/5.15.0/clang_64/mkspecs/features/device_config.prf:
../Qt/5.15.0/clang_64/mkspecs/common/unix.conf:
../Qt/5.15.0/clang_64/mkspecs/common/mac.conf:
../Qt/5.15.0/clang_64/mkspecs/common/macx.conf:
../Qt/5.15.0/clang_64/mkspecs/common/sanitize.conf:
../Qt/5.15.0/clang_64/mkspecs/common/gcc-base.conf:
../Qt/5.15.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt/5.15.0/clang_64/mkspecs/common/clang.conf:
../Qt/5.15.0/clang_64/mkspecs/common/clang-mac.conf:
../Qt/5.15.0/clang_64/mkspecs/qconfig.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.15.0/clang_64/mkspecs/features/qt_functions.prf:
../Qt/5.15.0/clang_64/mkspecs/features/qt_config.prf:
../Qt/5.15.0/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt/5.15.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.15.0/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.15.0/clang_64/mkspecs/features/mac/sdk.prf:
../Qt/5.15.0/clang_64/mkspecs/features/toolchain.prf:
../Qt/5.15.0/clang_64/mkspecs/features/mac/toolchain.prf:
../Qt/5.15.0/clang_64/mkspecs/features/default_pre.prf:
../Qt/5.15.0/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt/5.15.0/clang_64/mkspecs/features/resolve_config.prf:
../Qt/5.15.0/clang_64/mkspecs/features/default_post.prf:
../Qt/5.15.0/clang_64/mkspecs/features/mac/default_post.prf:
../Qt/5.15.0/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt/5.15.0/clang_64/mkspecs/features/resolve_target.prf:
../Qt/5.15.0/clang_64/mkspecs/features/unix/separate_debug_info.prf:
../Qt/5.15.0/clang_64/mkspecs/features/qtquickcompiler.prf:
../Qt/5.15.0/clang_64/mkspecs/features/qml_debug.prf:
../Qt/5.15.0/clang_64/mkspecs/features/mac/mac.prf:
../Qt/5.15.0/clang_64/mkspecs/features/warn_on.prf:
../Qt/5.15.0/clang_64/mkspecs/features/qt.prf:
../Qt/5.15.0/clang_64/mkspecs/features/resources_functions.prf:
../Qt/5.15.0/clang_64/mkspecs/features/resources.prf:
../Qt/5.15.0/clang_64/mkspecs/features/moc.prf:
../Qt/5.15.0/clang_64/mkspecs/features/unix/opengl.prf:
../Qt/5.15.0/clang_64/mkspecs/features/uic.prf:
../Qt/5.15.0/clang_64/mkspecs/features/unix/thread.prf:
../Qt/5.15.0/clang_64/mkspecs/features/qmake_use.prf:
../Qt/5.15.0/clang_64/mkspecs/features/file_copies.prf:
../Qt/5.15.0/clang_64/mkspecs/features/mac/rez.prf:
../Qt/5.15.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../Qt/5.15.0/clang_64/mkspecs/features/testcase_targets.prf:
../Qt/5.15.0/clang_64/mkspecs/features/exceptions.prf:
../Qt/5.15.0/clang_64/mkspecs/features/yacc.prf:
../Qt/5.15.0/clang_64/mkspecs/features/lex.prf:
../Calculator/Calculator.pro:
../Qt/5.15.0/clang_64/mkspecs/macx-clang/Info.plist.dSYM.in:
../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../Qt/5.15.0/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../Qt/5.15.0/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../Calculator/Calculator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qml_debug CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info

qmake_all: FORCE

Calculator.app/Contents/PkgInfo: 
	@test -d Calculator.app/Contents || mkdir -p Calculator.app/Contents
	@$(DEL_FILE) Calculator.app/Contents/PkgInfo
	@echo "APPL????" > Calculator.app/Contents/PkgInfo
Calculator.app/Contents/Resources/empty.lproj: 
	@test -d Calculator.app/Contents/Resources || mkdir -p Calculator.app/Contents/Resources
	@touch Calculator.app/Contents/Resources/empty.lproj
	
Calculator.app/Contents/Info.plist: 
	@test -d Calculator.app/Contents || mkdir -p Calculator.app/Contents
	@$(DEL_FILE) Calculator.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,Codemaze.Calculator,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},Codemaze.Calculator,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Calculator,g" -e "s,@LIBRARY@,Calculator,g" -e "s,\$${EXECUTABLE_NAME},Calculator,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../Qt/5.15.0/clang_64/mkspecs/macx-clang/Info.plist.app >Calculator.app/Contents/Info.plist

all: Makefile \
		Calculator.app/Contents/PkgInfo \
		Calculator.app/Contents/Resources/empty.lproj \
		Calculator.app/Contents/Info.plist Calculator.app/Contents/MacOS/Calculator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt/5.15.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Calculator/dialog.h ../Calculator/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Calculator/dialog.cpp ../Calculator/main.cpp ../Calculator/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Calculator/dialog.ui ../Calculator/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Calculator.app
	-$(DEL_FILE) /Users/Darek/build-Calculator-Desktop_Qt_5_15_0_clang_64bit-Profile/Calculator.app.dSYM/Contents/Resources/DWARF/Calculator .qmake.stash /Users/Darek/build-Calculator-Desktop_Qt_5_15_0_clang_64bit-Profile/Calculator.app.dSYM/Contents/Info.plist
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=x86_64 CONFIG+=qml_debug CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt/5.15.0/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h ../Qt/5.15.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_dialog.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_mainwindow.cpp
moc_dialog.cpp: ../Calculator/dialog.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		../Qt/5.15.0/clang_64/bin/moc
	/Users/Darek/Qt/5.15.0/clang_64/bin/moc $(DEFINES) --include /Users/Darek/build-Calculator-Desktop_Qt_5_15_0_clang_64bit-Profile/moc_predefs.h -I/Users/Darek/Qt/5.15.0/clang_64/mkspecs/macx-clang -I/Users/Darek/Calculator -I/Users/Darek/Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/Darek/Qt/5.15.0/clang_64/lib/QtGui.framework/Headers -I/Users/Darek/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/Darek/Qt/5.15.0/clang_64/lib ../Calculator/dialog.h -o moc_dialog.cpp

moc_mainwindow.cpp: ../Calculator/mainwindow.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Calculator/options.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		../Qt/5.15.0/clang_64/bin/moc
	/Users/Darek/Qt/5.15.0/clang_64/bin/moc $(DEFINES) --include /Users/Darek/build-Calculator-Desktop_Qt_5_15_0_clang_64bit-Profile/moc_predefs.h -I/Users/Darek/Qt/5.15.0/clang_64/mkspecs/macx-clang -I/Users/Darek/Calculator -I/Users/Darek/Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/Darek/Qt/5.15.0/clang_64/lib/QtGui.framework/Headers -I/Users/Darek/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/Darek/Qt/5.15.0/clang_64/lib ../Calculator/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h ui_mainwindow.h
ui_dialog.h: ../Calculator/dialog.ui \
		../Qt/5.15.0/clang_64/bin/uic
	/Users/Darek/Qt/5.15.0/clang_64/bin/uic ../Calculator/dialog.ui -o ui_dialog.h

ui_mainwindow.h: ../Calculator/mainwindow.ui \
		../Qt/5.15.0/clang_64/bin/uic
	/Users/Darek/Qt/5.15.0/clang_64/bin/uic ../Calculator/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

dialog.o: ../Calculator/dialog.cpp ../Calculator/dialog.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_dialog.h \
		../Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o ../Calculator/dialog.cpp

main.o: ../Calculator/main.cpp ../Calculator/mainwindow.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Calculator/options.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Calculator/main.cpp

mainwindow.o: ../Calculator/mainwindow.cpp ../Calculator/mainwindow.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Calculator/options.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_mainwindow.h \
		../Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QThread \
		../Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Calculator/dialog.h \
		../Qt/5.15.0/clang_64/lib/QtWidgets.framework/Headers/qwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../Calculator/mainwindow.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Calculator/bin || mkdir -p $(INSTALL_ROOT)/opt/Calculator/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app
	
	$(QINSTALL) Calculator.app $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Calculator/bin/ 


install_debug_info_plist_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents || mkdir -p $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents
	$(QINSTALL) /Users/Darek/build-Calculator-Desktop_Qt_5_15_0_clang_64bit-Profile/Calculator.app.dSYM/Contents/Info.plist $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents/Info.plist

uninstall_debug_info_plist_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents/Info.plist
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents/ 


install_debug_info_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents/Resources/DWARF || mkdir -p $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents/Resources/DWARF
	$(QINSTALL) /Users/Darek/build-Calculator-Desktop_Qt_5_15_0_clang_64bit-Profile/Calculator.app.dSYM/Contents/Resources/DWARF/Calculator $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents/Resources/DWARF/Calculator

uninstall_debug_info_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents/Resources/DWARF/Calculator
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app.dSYM/Contents/Resources/DWARF/ 


install: install_target install_debug_info_plist_target install_debug_info_target  FORCE

uninstall: uninstall_target uninstall_debug_info_plist_target uninstall_debug_info_target  FORCE

FORCE:

